language: cpp
sudo: false
compiler:
 - clang
 - gcc

dist: bionic
os: linux

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

addons:
  apt:
    update: true
    sources:
      - llvm-toolchain-bionic-8
    packages:
      - clang-6.0
      - libboost-all-dev
      - libyaml-cpp-dev
      - libmpfr-dev
      - libgmp-dev
      - libomp-dev
      - lcov

before_install:
  - pip install --user cpp-coveralls
  - export CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.tar.gz"
    rm -rf cmake && mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DBUILD_GOOGLE_TEST=ON  -DCOVERALLS=ON -DBUILD_CGAL=ON -DBUILD_HDF5=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j4
  - ctest -VV -R "Partikler_Test"
  - ./partikler --config=../example/SPH.yaml

