language: cpp
compiler: clang
dist: bionic

os: linux

before_install:
  - sudo apt install -y libyaml-cpp-dev libcgal-dev


script:
  - cmake --version
  - mkdir build && cd build && cmake .. && make
