language: cpp
sudo: false
compiler:
 - clang
 - gcc

dist: bionic
os: linux

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

addons:
  apt:
    update: true
    sources:
      - llvm-toolchain-bionic-8
    packages:
      - clang-6.0
      - cmake
      - libboost-all-dev
      - libyaml-cpp-dev
      - libmpfr-dev
      - libgmp-dev
      - libomp-dev

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DBUILD_GOOGLE_TEST=ON  -DBUILD_CGAL=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j4
  - ctest -R "Partikler_Test"
  - coveralls
  - ./partikler --config=../example/SPH.yaml

