language: cpp
sudo: false
compiler:
 - clang
 - gcc

dist: bionic
os: linux

addons:
  apt:
    update: true
    sources:
      - llvm-toolchain-bionic-8
    packages:
      - clang-6.0
      - cmake
      - libboost-all-dev
      - libyaml-cpp-dev
      - libmpfr-dev
      - libgmp-dev
      - libomp-dev

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DBUILD_GOOGLE_TEST=ON  -DBUILD_CGAL=ON ..
  - make -j4
  - ./partikler --config=../example/SPH.yaml
