language: cpp
compiler: clang
dist: bionic

os: linux

addons:
  apt:
    update: true
    sources:
      - llvm-toolchain-bionic-6.0
    packages:
      - clang-6.0
      - cmake

before_install:
  - sudo apt install -y libyaml-cpp-dev libcgal-dev


script:
  - cmake --version
  - mkdir build && cd build && cmake .. && make
